image: php:5.6

cache:
  paths:
  - vendor/
  - bower_components/

stages:
  - test
  - deploy

before_script:
- wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
- php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
- php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
- php composer-setup.php
- php -r "unlink('composer-setup.php'); unlink('installer.sig');"
- php composer.phar install

test:app:
  stage: test
  script:
  - php vendor/bin/phpunit --coverage-text --colors=never
  
deploy:app:
  stage: deploy
  script:
  - if [ -z "$webroot" ]; then echo "Need to set webroot" && exit 1; fi
  - sudo rsync -rv ./ $webroot --exclude '.git' --exclude '.gitlab-ci.yml' --exclude '.gitignore' --delete
  - sudo chown user:group $webroot -R