image: php:5.6

cache:
  paths:
  - vendor/
  - bower_components/
  - docs/cache

variables:
  - DOCS_FOLDER: "./docs"
  - SRC_FOLDER: "./res/php"

stages:
  - test
  - docs
  - deploy

test:phpunit:
  stage: test
  script:
  - wget -q https://getcomposer.org/composer.phar
  - php composer.phar install
  - php vendor/bin/phpunit --coverage-text --colors=never

docs:app:
  stage: docs
  script:
  - wget -q http://phpdoc.org/phpDocumentor.phar
  - mkdir -p $DOCS_FOLDER/api
  - php phpDocumentor.phar --directory $SRC_FOLDER/ --target $DOCS_FOLDER/api --cache-folder $DOCS_FOLDER/cache

deploy:frontend:
  stage: deploy
  script:
  - bower install

deploy:app:
  stage: deploy
  script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - ssh -p22 $SSH_HOST "mkdir -p $SSH_DIR"
  - rsync -rav -e ssh --exclude='.git/' --exclude='.gitlab-ci.yml' --exclude='*.phar' --exclude='$DOCS_FOLDER/cache' --delete-excluded ./ $SSH_HOST:$SSH_DIR