image: php:5.6

cache:
  paths:
  - vendor/
  - bower_components/
  - docs/cache

stages:
  - test
  - docs
  - deploy

test:app:
  stage: test
  script:
  - wget -q https://getcomposer.org/composer.phar
  - php composer.phar install
  - php vendor/bin/phpunit --coverage-text --colors=never

deploy:docs:
  stage: docs
  script:
  - wget -q http://phpdoc.org/phpDocumentor.phar
  - mkdir -p ./docs/api
  - php phpDocumentor.phar --directory ./res/php/ --target ./docs/api --cache-folder ./docs/cache

deploy:frontend:
  stage: deploy
  script:
  - bower install

deploy:app:
  stage: deploy
  script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - ssh -p22 $SSH_HOST "mkdir -p $SSH_DIR"
  - rsync -rav -e ssh --exclude='.git/' --exclude='.gitlab-ci.yml' --exclude='*.phar' --delete-excluded ./ $SSH_HOST:$SSH_DIR